# Site settings
title: ShadeofGod
description: "bing's blog about coding ..."
baseurl: "" # the subpath of your site
url: "http://shadeofgod.github.io"

# User settings
username: ShadeofGod
user_title: shadeofgod - coder
email: zoubingwu@gmail.com
github_username:  shadeofgod

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: mac terminal-like resume
    url: https://github.com/shadeofgod/resume
  - name: gobang
    url: https://github.com/shadeofgod/gobang
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
